---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-handler
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: update-handler
  template:
    metadata:
      labels:
        app: update-handler
    spec:
      serviceAccountName: bot
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          envFrom:
            - secretRef:
                name: secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 200m
